### ISSUE TITLE
呵呵

### ISSUE THREAD

**Issue by xiaoheshangnmsl** [frejs/fre-ie#1]
死🐎小和尚又开始了是吧？
专整这种装模做样的东西，搞的很几把牛逼的样子，实际fw到不行。
你说你目的就是搁群里朋友圈装逼呢， 也是，刚毕业爷也能理解，不过我刚毕业的时候都不敢你这么装，你这种的朋友圈老子利索就拉黑了，一大把人等着挨个喷你呢，弟弟。
建议直接去造火箭，可不能耽误人才。

**Comment by wuxiongzhi** [comment]
干得漂亮

**Comment by xiaoheshangnbsl** [comment]
不愧是基佬，这么喜欢说🐦语。
